### ISSUE TITLE
file_num missing from eodr_naming

### ISSUE THREAD

**Issue by lforesta** [TUW-GEO/geopathfinder#11]
file_num is not any more a keyword in eodr_naming, which breaks functionality. Maybe it was deleted by mistake in the latest changes?
@claxn

**Comment by cnavacch** [comment]
Thanks for finding this bug. I have added it again to the class and tests. Could you please test if everything works for you as expected (branch `eodr_hotfix`)? If so, then we can merge it to `master`.
