### ISSUE TITLE
python-dateutil version clashes with pandas

### ISSUE THREAD

**Issue by lforesta** [TUW-GEO/geopathfinder#18]
python-dateutil version is fixed (`python-dateutil==2.6.1`) but pandas now requires `python-dateutil>=2.7.3`

Is it possible to relax the version to `python-dateutil>=2.6.1` or upgrade it directly?

**Comment by bbauerma** [comment]
is closed with [commit](https://github.com/TUW-GEO/geopathfinder/commit/33fa81175f0e084f31aa1d435a86f7830b937b2b)
