### ISSUE TITLE
"---" as orbit number should be valid in sgrt file naming

### ISSUE THREAD

**Issue by tobiasstachl** [TUW-GEO/geopathfinder#19]
Only integer values are currently valid for the relative orbit number. But for sgrt parameters, where no orbit number is defined in the filename ("_---_"), the function decode_rel_orbit() in sgrt_naming.py is failing because it tries to cast the string to int.

**Comment by cnavacch** [comment]
@tobiasstachl : I am surprised this still happens. I fixed this issue some time ago, now there is even a test for it:
https://github.com/TUW-GEO/geopathfinder/blob/2f308bc82e48fe2b3e68447c2f8dc4ed76ff8fc5/tests/test_sgrt_naming.py#L165
Are you sure you use geopathfinder==0.6? If this is the case can you try installing from the master branch?

**Comment by cnavacch** [comment]
`geopathfinder == 0.6` seems to work.
