### ISSUE TITLE
Fix license.txt

### ISSUE THREAD

**Issue by sebhahn** [TUW-GEO/geopathfinder#8]
Update license.txt with correct names

**Comment by sebhahn** [comment]
This is issue not fixed?

**Comment by bbauerma** [comment]
i don't see any problem. if it's still an issue, please specify more detailed, or better - fix it directly ;-)

**Comment by sebhahn** [comment]
Your name is in the license file.

**Comment by bbauerma** [comment]
is done now.
des häst aber wirkli gach selber korrigieren können, statt dass du da die git-bürokratie anwirfst.... ;-)
